name: Test

on:
  push:
    branches: [ master ]

jobs:
  test_env:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Debug action
        uses: hmarr/debug-action@v2.0.0
